spring:
  thymeleaf:
    mode: HTML

  profiles:
    active: pro

comment:
  avatar: /images/avatar.png

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count